
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Admin
 */
public class fund extends javax.swing.JFrame {

      Connection con=null;
    
    Statement st=null;

    public fund() {
        initComponents();
        connect();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        f_amt = new javax.swing.JTextField();
        emp_id = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        save_bt = new javax.swing.JButton();
        f_name = new javax.swing.JComboBox<>();
        j_date = new com.toedter.calendar.JDateChooser();
        delete_bt1 = new javax.swing.JButton();
        validation1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        f_table = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/managed-services-banner.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1359, 200));

        jPanel1.setBackground(new java.awt.Color(153, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 51, 153));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/back.png"))); // NOI18N
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, -1));

        jLabel10.setFont(new java.awt.Font("Gabriola", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 102));
        jLabel10.setText("FUND  NAME :");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, -1, -1));

        jLabel11.setFont(new java.awt.Font("Gabriola", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 102));
        jLabel11.setText("FUND  AMOUNT :");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 280, -1, -1));

        jLabel12.setFont(new java.awt.Font("Gabriola", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 102));
        jLabel12.setText(" DATE :");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 350, -1, -1));

        jLabel13.setFont(new java.awt.Font("Gabriola", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 102));
        jLabel13.setText("EMPLOYEE  ID :");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, -1, -1));

        f_amt.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        f_amt.setForeground(new java.awt.Color(255, 0, 102));
        f_amt.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 51, 153)));
        f_amt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f_amtActionPerformed(evt);
            }
        });
        jPanel1.add(f_amt, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 280, 190, -1));

        emp_id.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        emp_id.setForeground(new java.awt.Color(255, 0, 102));
        emp_id.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 51, 153)));
        emp_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emp_idActionPerformed(evt);
            }
        });
        emp_id.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                emp_idKeyPressed(evt);
            }
        });
        jPanel1.add(emp_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 140, 190, -1));

        jLabel20.setFont(new java.awt.Font("Segoe Script", 1, 36)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 0, 102));
        jLabel20.setText("Fund  Chart");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 20, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/butter.gif"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 20, 580, 560));

        save_bt.setBackground(new java.awt.Color(153, 255, 255));
        save_bt.setFont(new java.awt.Font("Segoe Script", 1, 24)); // NOI18N
        save_bt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/save2.gif"))); // NOI18N
        save_bt.setText("Save");
        save_bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save_btActionPerformed(evt);
            }
        });
        jPanel1.add(save_bt, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 420, 180, 70));

        f_name.setFont(new java.awt.Font("Gabriola", 1, 24)); // NOI18N
        f_name.setForeground(new java.awt.Color(255, 0, 51));
        f_name.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<SELECT>", "Provident Fund(PF)", "Fixed IncomeFund", "Balanced Fund" }));
        f_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f_nameActionPerformed(evt);
            }
        });
        jPanel1.add(f_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 210, 190, 40));

        j_date.setFont(new java.awt.Font("Gabriola", 1, 24)); // NOI18N
        jPanel1.add(j_date, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 350, 190, 40));

        delete_bt1.setBackground(new java.awt.Color(153, 255, 255));
        delete_bt1.setFont(new java.awt.Font("Segoe Script", 1, 24)); // NOI18N
        delete_bt1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/delete1.png"))); // NOI18N
        delete_bt1.setText("Delete");
        delete_bt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_bt1ActionPerformed(evt);
            }
        });
        jPanel1.add(delete_bt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 420, 190, 70));

        validation1.setFont(new java.awt.Font("Gabriola", 1, 24)); // NOI18N
        jPanel1.add(validation1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 180, 120, 20));

        jButton2.setBackground(new java.awt.Color(153, 255, 255));
        jButton2.setFont(new java.awt.Font("Segoe Script", 1, 18)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/update10.png"))); // NOI18N
        jButton2.setText("Update");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 270, 190, 70));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/search.gif"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 130, 60, 50));

        f_table.setBackground(new java.awt.Color(153, 255, 255));
        f_table.setFont(new java.awt.Font("Gabriola", 1, 24)); // NOI18N
        f_table.setText("Display");
        f_table.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f_tableActionPerformed(evt);
            }
        });
        jPanel1.add(f_table, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, 190, 70));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 1370, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new home().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void f_amtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f_amtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_f_amtActionPerformed

    private void emp_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emp_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emp_idActionPerformed

    private void save_btActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save_btActionPerformed
        // TODO add your handling code here:
        String empid = emp_id.getText().toString();
        String fundname =(String) f_name.getSelectedItem();
        String fundamt = f_amt.getText().toString();
        SimpleDateFormat sdf =new SimpleDateFormat("yyyy-MM-dd");
        String funddate=sdf.format(j_date.getDate());
        String insert1="insert into fund values('"+Integer.parseInt(empid)+"','"+fundname+"','"+fundamt+"','"+funddate+"');";
        try{
            st.execute(insert1);
            JOptionPane.showMessageDialog(null,"value inserted successfully");
            
            emp_id.setText("");
        f_amt.setText("");
       
        f_name.setSelectedItem(null);
        
        j_date.setCalendar(null);
        
           
        }
        
         catch (Exception e){
             JOptionPane.showMessageDialog(null, e);
         }  
        
        
    }//GEN-LAST:event_save_btActionPerformed

    private void delete_bt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_bt1ActionPerformed
        // TODO add your handling code here:
        String empid=emp_id.getText().toString();
        String del="delete from fund where emp_id='"+empid+"';";
        try{
            st.executeUpdate(del);
            JOptionPane.showMessageDialog(null,"Value Deleted Successfully");
            
            emp_id.setText("");
        f_amt.setText("");
       
        f_name.setSelectedItem(null);
        
        j_date.setCalendar(null);

        }

        catch (Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_delete_bt1ActionPerformed

    private void emp_idKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_emp_idKeyPressed
        // TODO add your handling code here:
        try{
            int i=Integer.parseInt(emp_id.getText());
            validation1.setText(""); 
        }
        catch(NumberFormatException e){
          validation1.setText("Invalid number");  
        }
    }//GEN-LAST:event_emp_idKeyPressed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String empid=emp_id.getText();
        String fundname=(String)f_name.getSelectedItem();
        String fundamt=f_amt.getText();
         SimpleDateFormat sdf =new SimpleDateFormat("yyyy-MM-dd");
         String funddate=sdf.format(j_date.getDate());
         
         
        try{
           
            String query="update fund set fund_name='"+fundname+"',fund_amt='"+fundamt+"',fund_date='"+funddate+"'  where emp_id='"+Integer.parseInt(empid)+"';";
            
           
            st.executeUpdate(query);
           JOptionPane.showMessageDialog(null,"successfully updated");
              emp_id.setText(null);
           j_date.setCalendar(null);
           
           f_amt.setText(null);
            
        }
        catch (Exception e){
            JOptionPane.showMessageDialog(null, e);
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
         try{
          String sql="select * from fund where emp_id=?";
          PreparedStatement pstmt=con.prepareStatement(sql);
          pstmt.setInt(1,Integer.parseInt(emp_id.getText()));
          ResultSet rs=pstmt.executeQuery();
          
          if(rs.next())
          {
              String date=rs.getString("fund_date");
              f_name.setSelectedItem(rs.getString("fund_name"));
              f_amt.setText(rs.getString("fund_amt"));
              ((JTextField)j_date.getDateEditor().getUiComponent()).setText(date);
              
          }
           
          else
          
          {
            JOptionPane.showMessageDialog(null,"Record not found ");  
          }
            
        }
        catch (Exception e){
             JOptionPane.showMessageDialog(null,e);
         }  
    }//GEN-LAST:event_jButton3ActionPerformed

    private void f_tableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f_tableActionPerformed
        // TODO add your handling code here:
        new fund_table().setVisible(true);
        dispose();
    }//GEN-LAST:event_f_tableActionPerformed

    private void f_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_f_nameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fund.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fund.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fund.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fund.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fund().setVisible(true);
            }
        });
    }
    
    public void connect()
    {
       try
        {
            Class.forName("com.mysql.jdbc.Driver").newInstance();
            con=DriverManager.getConnection("jdbc:mysql://localhost:3306/pay","root","root");
                   st=con.createStatement();
            
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton delete_bt1;
    private javax.swing.JTextField emp_id;
    private javax.swing.JTextField f_amt;
    private javax.swing.JComboBox<String> f_name;
    private javax.swing.JButton f_table;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JPanel jPanel1;
    private com.toedter.calendar.JDateChooser j_date;
    private javax.swing.JButton save_bt;
    private javax.swing.JLabel validation1;
    // End of variables declaration//GEN-END:variables
}
