/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Admin
 */
public class home extends javax.swing.JFrame {

    /**
     * Creates new form home
     */
    public home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        hom_ban = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        pay_info = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        insert_bt = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        querie = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe Script", 1, 48)); // NOI18N
        jLabel1.setText("Salary  Management");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 70, 550, -1));

        hom_ban.setIcon(new javax.swing.ImageIcon(getClass().getResource("/managed-services-banner.jpg"))); // NOI18N
        getContentPane().add(hom_ban, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1350, 208));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pay_info.setBackground(new java.awt.Color(153, 255, 255));
        pay_info.setFont(new java.awt.Font("Segoe Script", 1, 24)); // NOI18N
        pay_info.setIcon(new javax.swing.ImageIcon(getClass().getResource("/payment.png"))); // NOI18N
        pay_info.setText("Salary");
        pay_info.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pay_infoActionPerformed(evt);
            }
        });
        jPanel1.add(pay_info, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 230, 240, 90));

        jButton5.setBackground(new java.awt.Color(153, 255, 255));
        jButton5.setFont(new java.awt.Font("Segoe Script", 1, 24)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Absence1.gif"))); // NOI18N
        jButton5.setText("Leave");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 90, 240, 90));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/payroll.png"))); // NOI18N
        jLabel2.setText("Pat");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 20, 480, 480));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/r3r3.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 60, 600, 360));

        insert_bt.setBackground(new java.awt.Color(153, 255, 255));
        insert_bt.setFont(new java.awt.Font("Segoe Script", 1, 24)); // NOI18N
        insert_bt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adddd.gif"))); // NOI18N
        insert_bt.setText("Employe");
        insert_bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insert_btActionPerformed(evt);
            }
        });
        jPanel1.add(insert_bt, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 90, 230, 90));

        jButton1.setBackground(new java.awt.Color(153, 255, 255));
        jButton1.setFont(new java.awt.Font("Segoe Script", 1, 24)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fund2.gif"))); // NOI18N
        jButton1.setText("Fund");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, 230, 90));

        querie.setBackground(new java.awt.Color(153, 255, 255));
        querie.setFont(new java.awt.Font("Segoe Script", 1, 24)); // NOI18N
        querie.setText("Queries");
        querie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                querieActionPerformed(evt);
            }
        });
        jPanel1.add(querie, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 380, 230, 70));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 1350, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void insert_btActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insert_btActionPerformed
        // TODO add your handling code here:
        dispose();
        
      new insert().setVisible(true);
    }//GEN-LAST:event_insert_btActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         dispose();
        
      new fund().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void pay_infoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pay_infoActionPerformed
        // TODO add your handling code here:
         dispose();
        
      new salary1().setVisible(true);
    }//GEN-LAST:event_pay_infoActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
              dispose();
        
      new leave().setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void querieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_querieActionPerformed
        // TODO add your handling code here:
    dispose();
        
      new Queries().setVisible(true);    
        
    
    }//GEN-LAST:event_querieActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel hom_ban;
    private javax.swing.JButton insert_bt;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton pay_info;
    private javax.swing.JButton querie;
    // End of variables declaration//GEN-END:variables
}
