
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Admin
 */
public class salary1 extends javax.swing.JFrame {
Connection con=null;
    String gender;
    
    Statement st=null;
    ResultSet rs=null;
    PreparedStatement pst=null;
    /**
     * Creates new form salary1
     */
    public salary1() {
        initComponents();
        connect();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        emp_id = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        desig = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        iu = new javax.swing.JLabel();
        c = new javax.swing.JTextField();
        a = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        b = new javax.swing.JTextField();
        d = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        dd = new javax.swing.JTextField();
        cc = new javax.swing.JTextField();
        aa = new javax.swing.JTextField();
        bb = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        ee = new javax.swing.JLabel();
        emp_name = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txt_search = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        save_bt = new javax.swing.JButton();
        ddd = new javax.swing.JLabel();
        jdc = new com.toedter.calendar.JDateChooser();
        delete_bt = new javax.swing.JButton();
        clear_bt = new javax.swing.JButton();
        sal_tab = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1360, 720));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/managed-services-banner.jpg"))); // NOI18N

        jPanel1.setBackground(new java.awt.Color(102, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 51, 153));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/back.png"))); // NOI18N
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel18.setFont(new java.awt.Font("Gabriola", 1, 24)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 0, 102));
        jLabel18.setText("DATE  OF  PAYMENT :");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 70, -1, -1));

        jLabel20.setFont(new java.awt.Font("Segoe Script", 1, 36)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 0, 102));
        jLabel20.setText("Salary  Details");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 20, -1, -1));

        emp_id.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        emp_id.setForeground(new java.awt.Color(255, 0, 102));
        emp_id.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 51, 153)));
        emp_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emp_idActionPerformed(evt);
            }
        });
        jPanel1.add(emp_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 140, 120, -1));

        jLabel21.setFont(new java.awt.Font("Gabriola", 1, 24)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 0, 102));
        jLabel21.setText("EMPLOYEE  ID :");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, -1, -1));

        desig.setEditable(false);
        desig.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        desig.setForeground(new java.awt.Color(255, 0, 102));
        desig.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 51, 153)));
        desig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                desigActionPerformed(evt);
            }
        });
        jPanel1.add(desig, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 140, 190, -1));

        jLabel4.setFont(new java.awt.Font("Gabriola", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 102));
        jLabel4.setText("EMPLOYEE  NAME :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 140, 180, 40));

        jLabel8.setFont(new java.awt.Font("Gabriola", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 102));
        jLabel8.setText("DESIGNATION :");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 140, -1, -1));

        jPanel2.setBackground(new java.awt.Color(204, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel22.setFont(new java.awt.Font("Gabriola", 1, 24)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 0, 102));
        jLabel22.setText("Earnings");
        jPanel2.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 20, -1, -1));

        jLabel5.setFont(new java.awt.Font("Gabriola", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 102));
        jLabel5.setText("BASIC  SALARY :");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        jLabel6.setFont(new java.awt.Font("Gabriola", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 102));
        jLabel6.setText("EARNINGS");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, -1, -1));

        jLabel7.setFont(new java.awt.Font("Gabriola", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 102));
        jLabel7.setText("DA  :");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, -1, -1));

        iu.setFont(new java.awt.Font("Gabriola", 1, 18)); // NOI18N
        iu.setForeground(new java.awt.Color(0, 0, 102));
        iu.setText("GROSS TOTAL:");
        iu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iuMouseClicked(evt);
            }
        });
        jPanel2.add(iu, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, -1, -1));

        c.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        c.setForeground(new java.awt.Color(255, 0, 102));
        c.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 51, 153)));
        c.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cActionPerformed(evt);
            }
        });
        c.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cKeyTyped(evt);
            }
        });
        jPanel2.add(c, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 150, 30));

        a.setEditable(false);
        a.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        a.setForeground(new java.awt.Color(255, 0, 102));
        a.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 51, 153)));
        a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aActionPerformed(evt);
            }
        });
        jPanel2.add(a, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 150, 30));

        jLabel17.setFont(new java.awt.Font("Gabriola", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 102));
        jLabel17.setText("HRA  :");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, -1, -1));

        b.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        b.setForeground(new java.awt.Color(255, 0, 102));
        b.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 51, 153)));
        b.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                bComponentAdded(evt);
            }
        });
        b.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                bFocusLost(evt);
            }
        });
        b.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bMouseExited(evt);
            }
        });
        b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bActionPerformed(evt);
            }
        });
        b.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                bPropertyChange(evt);
            }
        });
        b.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                bKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                bKeyTyped(evt);
            }
        });
        jPanel2.add(b, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 150, 30));

        d.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jPanel2.add(d, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, 110, 40));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 220, 320, 360));

        jPanel3.setBackground(new java.awt.Color(204, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Gabriola", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 102));
        jLabel10.setText("DEDUCTION ");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, -1, -1));

        jLabel11.setFont(new java.awt.Font("Gabriola", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 102));
        jLabel11.setText("PF  :");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, -1, -1));

        jLabel12.setFont(new java.awt.Font("Gabriola", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 102));
        jLabel12.setText(" PROFESSION TAX :");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));

        jLabel13.setFont(new java.awt.Font("Gabriola", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 102));
        jLabel13.setText(" ESI :");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, -1, -1));

        jLabel14.setFont(new java.awt.Font("Gabriola", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 102));
        jLabel14.setText(" LOAN :");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, -1, -1));

        dd.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        dd.setForeground(new java.awt.Color(255, 0, 102));
        dd.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 51, 153)));
        dd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ddActionPerformed(evt);
            }
        });
        dd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ddKeyReleased(evt);
            }
        });
        jPanel3.add(dd, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, 130, 30));

        cc.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        cc.setForeground(new java.awt.Color(255, 0, 102));
        cc.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 51, 153)));
        cc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ccActionPerformed(evt);
            }
        });
        jPanel3.add(cc, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, 130, 30));

        aa.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        aa.setForeground(new java.awt.Color(255, 0, 102));
        aa.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 51, 153)));
        aa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aaActionPerformed(evt);
            }
        });
        jPanel3.add(aa, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, 130, 30));

        bb.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        bb.setForeground(new java.awt.Color(255, 0, 102));
        bb.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 51, 153)));
        bb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bbActionPerformed(evt);
            }
        });
        jPanel3.add(bb, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, 130, 30));

        jLabel16.setFont(new java.awt.Font("Gabriola", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 102));
        jLabel16.setText("TOTAL DEDUCTION :");
        jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel16MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));

        ee.setFont(new java.awt.Font("MV Boli", 1, 24)); // NOI18N
        ee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eeMouseClicked(evt);
            }
        });
        ee.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                eeKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                eeKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                eeKeyTyped(evt);
            }
        });
        jPanel3.add(ee, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, 130, 40));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 220, 330, 360));

        emp_name.setEditable(false);
        emp_name.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        emp_name.setForeground(new java.awt.Color(255, 0, 102));
        emp_name.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 51, 153)));
        emp_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emp_nameActionPerformed(evt);
            }
        });
        jPanel1.add(emp_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 140, 190, -1));

        jLabel15.setFont(new java.awt.Font("Gabriola", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 102));
        jLabel15.setText("NET  SALARY :");
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel15MouseClicked(evt);
            }
        });
        jLabel15.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jLabel15KeyPressed(evt);
            }
        });
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 420, -1, -1));

        txt_search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_searchKeyReleased(evt);
            }
        });
        jPanel1.add(txt_search, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 10, 70, 20));

        jButton2.setBackground(new java.awt.Color(102, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/search.gif"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 130, 50, 50));

        save_bt.setBackground(new java.awt.Color(204, 204, 204));
        save_bt.setFont(new java.awt.Font("Gabriola", 1, 24)); // NOI18N
        save_bt.setText("Save");
        save_bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save_btActionPerformed(evt);
            }
        });
        jPanel1.add(save_bt, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 470, -1, 40));

        ddd.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        ddd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dddMouseClicked(evt);
            }
        });
        jPanel1.add(ddd, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 410, 150, 40));

        jdc.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanel1.add(jdc, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 70, 170, 40));

        delete_bt.setFont(new java.awt.Font("Gabriola", 1, 24)); // NOI18N
        delete_bt.setText("Delete");
        delete_bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_btActionPerformed(evt);
            }
        });
        jPanel1.add(delete_bt, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 470, -1, 40));

        clear_bt.setFont(new java.awt.Font("Gabriola", 1, 24)); // NOI18N
        clear_bt.setText("Clear");
        clear_bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clear_btActionPerformed(evt);
            }
        });
        jPanel1.add(clear_bt, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 420, 120, 40));

        sal_tab.setFont(new java.awt.Font("Gabriola", 1, 24)); // NOI18N
        sal_tab.setText("Display");
        sal_tab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sal_tabActionPerformed(evt);
            }
        });
        jPanel1.add(sal_tab, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 470, 110, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 621, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new home().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void emp_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emp_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emp_idActionPerformed

    private void desigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_desigActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_desigActionPerformed

    private void cActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cActionPerformed

    private void aActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aActionPerformed

    private void bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bActionPerformed
      
    }//GEN-LAST:event_bActionPerformed

    private void ddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ddActionPerformed

    private void ccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ccActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ccActionPerformed

    private void aaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aaActionPerformed

    private void bbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bbActionPerformed

    private void emp_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emp_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emp_nameActionPerformed

    private void txt_searchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_searchKeyReleased
        // TODO add your handling code here:

    }//GEN-LAST:event_txt_searchKeyReleased

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
          try{
          String sql="select * from employee where emp_id=?";
          PreparedStatement pstmt=con.prepareStatement(sql);
          pstmt.setInt(1,Integer.parseInt(emp_id.getText()));
          ResultSet rs=pstmt.executeQuery();
          if(rs.next())
          {
              emp_name.setText(rs.getString("emp_name"));
              desig.setText(rs.getString("designation"));
              a.setText(rs.getString("basic_salary"));
              
           
              
              
          }
          else
          
          {
            JOptionPane.showMessageDialog(null,"Record not found ");  
          }
            
        }
        catch (Exception e){
             JOptionPane.showMessageDialog(null,e);
         } 
    }//GEN-LAST:event_jButton2ActionPerformed

    private void iuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iuMouseClicked
        // TODO add your handling code here:
        //double e=Double.parseDouble(a.getText());
       
       //double f=Double.parseDouble(b.getText());
       //double g=Double.parseDouble(c.getText());
       //double h=e+f+g;
       //d.setText(h+" ");
        
    }//GEN-LAST:event_iuMouseClicked

    private void bKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bKeyTyped
       
    }//GEN-LAST:event_bKeyTyped

    private void bKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bKeyReleased
 
    }//GEN-LAST:event_bKeyReleased

    private void bComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_bComponentAdded
 
    }//GEN-LAST:event_bComponentAdded

    private void bFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_bFocusLost
       
    }//GEN-LAST:event_bFocusLost

    private void bPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_bPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_bPropertyChange

    private void bMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bMouseExited

    }//GEN-LAST:event_bMouseExited

    private void dddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dddMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_dddMouseClicked

    private void eeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eeMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_eeMouseClicked

    private void jLabel16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseClicked
        // TODO add your handling code here:
        //double f=Double.parseDouble(aa.getText());
       
       //double g=Double.parseDouble(bb.getText());
       //double h=Double.parseDouble(cc.getText());
       //double i=Double.parseDouble(dd.getText());
       //double j=f+g+h+i;
       //ee.setText(j+" ");
    }//GEN-LAST:event_jLabel16MouseClicked

    private void jLabel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseClicked
        // TODO add your handling code here:
        double aaa =Double.parseDouble(d.getText());
       
       double bbb =Double.parseDouble(ee.getText());
       
       double ccc=aaa-bbb;
       ddd.setText(ccc+" ");
    }//GEN-LAST:event_jLabel15MouseClicked

    private void save_btActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save_btActionPerformed
        // TODO add your handling code here:
        String empid = emp_id.getText().toString();
       String empname = emp_name.getText().toString();
       String Designation = desig.getText().toString();
       SimpleDateFormat sdf =new SimpleDateFormat("yyyy-MM-dd");
        String pay_Date=sdf.format(jdc.getDate());
       
       String Salary = a.getText().toString();
       String hra = b.getText().toString();
       String da = c.getText().toString();
       String gross_tot = d.getText().toString();
       String pf = aa.getText().toString();
       String esi = bb.getText().toString();
       String loan = cc.getText().toString();
       String tax = dd.getText().toString();
       String tot_ded = ee.getText().toString();
       String net_sal = ddd.getText().toString();
       
       String insert="insert into salary values('"+Integer.parseInt(empid)+"','"+empname+"','"+Designation+"','"+pay_Date+"','"+Salary+"','"+hra+"','"+da+"','"+Double.valueOf(gross_tot).doubleValue()+"','"+pf +"','"+esi+"','"+loan+"','"+tax+"','"+Double.valueOf(tot_ded).doubleValue()+"','"+Double.valueOf(net_sal).doubleValue()+"');"; 
       
       
        try{
            st.execute(insert);
            JOptionPane.showMessageDialog(null,"value inserted successfully");
            
            emp_id.setText("");
        emp_name.setText("");
        a.setText("");
        b.setText("");
        c.setText("");
        aa.setText("");
        desig.setText("");
        dd.setText("");
        cc.setText("");
        bb.setText("");
        jdc.setCalendar(null);
        d.setText("");
        ee.setText("");
        ddd.setText("");
           
        }
        
         catch (Exception e){
             JOptionPane.showMessageDialog(null, e);
         } 
    }//GEN-LAST:event_save_btActionPerformed

    private void delete_btActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_btActionPerformed
        // TODO add your handling code here:
         String empid=emp_id.getText().toString();
        String del="delete from salary where emp_id='"+empid+"';";
        try{
            st.executeUpdate(del);
            JOptionPane.showMessageDialog(null,"Value Deleted Successfully");
            
            emp_id.setText("");
        emp_name.setText("");
        a.setText("");
        b.setText("");
        c.setText("");
        aa.setText("");
        desig.setText("");
        dd.setText("");
        cc.setText("");
        bb.setText("");
        jdc.setCalendar(null);
        d.setText("");
        ee.setText("");
        ddd.setText("");

        }

        catch (Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_delete_btActionPerformed

    private void clear_btActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clear_btActionPerformed
        // TODO add your handling code here:
       emp_id.setText("");
        emp_name.setText("");
        a.setText("");
        b.setText("");
        c.setText("");
        aa.setText("");
        desig.setText("");
        dd.setText("");
        cc.setText("");
        bb.setText("");
        jdc.setCalendar(null);
        d.setText("");
        ee.setText("");
        ddd.setText("");
    }//GEN-LAST:event_clear_btActionPerformed

    private void cKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cKeyPressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_cKeyPressed

    private void cKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cKeyReleased
        // TODO add your handling code here:
        double e=Double.parseDouble(a.getText());
       
       double f=Double.parseDouble(b.getText());
       double g=Double.parseDouble(c.getText());
       double h=e+f+g;
       d.setText(h+" ");
    }//GEN-LAST:event_cKeyReleased

    private void cKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cKeyTyped
        // TODO add your handling code here:
        
    }//GEN-LAST:event_cKeyTyped

    private void ddKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ddKeyReleased
        // TODO add your handling code here:
        double f=Double.parseDouble(aa.getText());
       
       double g=Double.parseDouble(bb.getText());
       double h=Double.parseDouble(cc.getText());
       double i=Double.parseDouble(dd.getText());
       double j=f+g+h+i;
       ee.setText(j+" ");
    }//GEN-LAST:event_ddKeyReleased

    private void eeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_eeKeyTyped
        // TODO add your handling code here:
        
    }//GEN-LAST:event_eeKeyTyped

    private void eeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_eeKeyReleased
        // TODO add your handling code here:
        
    }//GEN-LAST:event_eeKeyReleased

    private void eeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_eeKeyPressed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_eeKeyPressed

    private void jLabel15KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLabel15KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel15KeyPressed

    private void sal_tabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sal_tabActionPerformed
        // TODO add your handling code here:
        new sal_table().setVisible(true);
        dispose();
    }//GEN-LAST:event_sal_tabActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(salary1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(salary1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(salary1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(salary1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new salary1().setVisible(true);
            }
        });
    }
     public void connect()
    {
       try
        {
            Class.forName("com.mysql.jdbc.Driver").newInstance();
            con=DriverManager.getConnection("jdbc:mysql://localhost:3306/pay","root","root");
                   st=con.createStatement();
            
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField a;
    private javax.swing.JTextField aa;
    private javax.swing.JTextField b;
    private javax.swing.JTextField bb;
    private javax.swing.JTextField c;
    private javax.swing.JTextField cc;
    private javax.swing.JButton clear_bt;
    private javax.swing.JLabel d;
    private javax.swing.JTextField dd;
    private javax.swing.JLabel ddd;
    private javax.swing.JButton delete_bt;
    private javax.swing.JTextField desig;
    private javax.swing.JLabel ee;
    private javax.swing.JTextField emp_id;
    private javax.swing.JTextField emp_name;
    private javax.swing.JLabel iu;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private com.toedter.calendar.JDateChooser jdc;
    private javax.swing.JButton sal_tab;
    private javax.swing.JButton save_bt;
    private javax.swing.JLabel txt_search;
    // End of variables declaration//GEN-END:variables
}
